"""baseline schema

Revision ID: ae8bd2a26bb2
Revises: 
Create Date: 2026-06-01 14:17:33.735157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8bd2a26bb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha')
    )
    with op.batch_alter_table('festivos', schema=None) as batch_op:
        batch_op.create_index('idx_festivo_activo_fecha', ['activo', 'fecha'], unique=False)

    op.create_table('tipos_ausencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('max_dias', sa.Integer(), nullable=True),
    sa.Column('tipo_dias', sa.String(length=20), nullable=True),
    sa.Column('requiere_justificante', sa.Boolean(), nullable=True),
    sa.Column('descuenta_vacaciones', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('dias_vacaciones', sa.Integer(), nullable=True),
    sa.Column('fecha_alta', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index('idx_usuario_activo', ['activo'], unique=False)
        batch_op.create_index('idx_usuario_email', ['email'], unique=False)

    op.create_table('aprobadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('aprobador_id', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aprobador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('nombre_almacenado', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('tamano_bytes', sa.Integer(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('ruta_relativa', sa.String(length=500), nullable=False),
    sa.Column('tipo_entidad', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado_por', sa.Integer(), nullable=True),
    sa.Column('motivo_eliminacion', sa.String(length=255), nullable=True),
    sa.Column('publico', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['eliminado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_almacenado')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index('idx_attachment_entidad', ['tipo_entidad', 'entidad_id', 'activo'], unique=False)
        batch_op.create_index('idx_attachment_usuario', ['uploaded_by', 'fecha_subida'], unique=False)

    op.create_table('cambios_saldo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=100), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('dias_anteriores', sa.Integer(), nullable=False),
    sa.Column('dias_nuevos', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cambios_saldo', schema=None) as batch_op:
        batch_op.create_index('idx_cambio_saldo_fecha', ['fecha'], unique=False)
        batch_op.create_index('idx_cambio_saldo_usuario', ['usuario_id'], unique=False)

    op.create_table('fichajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('es_actual', sa.Boolean(), nullable=False),
    sa.Column('tipo_accion', sa.String(length=20), nullable=True),
    sa.Column('motivo_rectificacion', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('editor_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_entrada', sa.Time(), nullable=False),
    sa.Column('hora_salida', sa.Time(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('pausa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['editor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fichajes', schema=None) as batch_op:
        batch_op.create_index('idx_fichaje_fecha', ['fecha'], unique=False)
        batch_op.create_index('idx_fichaje_grupo', ['grupo_id'], unique=False)
        batch_op.create_index('idx_fichaje_usuario_fecha', ['usuario_id', 'es_actual', 'fecha'], unique=False)

    op.create_table('saldos_vacaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('dias_totales', sa.Integer(), nullable=True),
    sa.Column('dias_disfrutados', sa.Integer(), nullable=True),
    sa.Column('dias_carryover', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'anio', name='unique_usuario_anio')
    )
    with op.batch_alter_table('saldos_vacaciones', schema=None) as batch_op:
        batch_op.create_index('idx_saldo_anio', ['anio'], unique=False)
        batch_op.create_index('idx_saldo_usuario_anio', ['usuario_id', 'anio'], unique=False)

    op.create_table('solicitudes_bajas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('es_actual', sa.Boolean(), nullable=False),
    sa.Column('motivo_rectificacion', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_ausencia_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('dias_solicitados', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(), nullable=True),
    sa.Column('aprobador_id', sa.Integer(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['aprobador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_ausencia_id'], ['tipos_ausencia.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitudes_bajas', schema=None) as batch_op:
        batch_op.create_index('idx_bajas_grupo', ['grupo_id'], unique=False)
        batch_op.create_index('idx_bajas_solape', ['usuario_id', 'es_actual', 'estado', 'fecha_inicio', 'fecha_fin'], unique=False)

    op.create_table('solicitudes_vacaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('es_actual', sa.Boolean(), nullable=False),
    sa.Column('motivo_rectificacion', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('dias_solicitados', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(), nullable=True),
    sa.Column('aprobador_id', sa.Integer(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('tipo_accion', sa.String(length=20), nullable=True),
    sa.Column('editor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aprobador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['editor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitudes_vacaciones', schema=None) as batch_op:
        batch_op.create_index('idx_vacaciones_grupo', ['grupo_id'], unique=False)
        batch_op.create_index('idx_vacaciones_solape', ['usuario_id', 'es_actual', 'estado', 'fecha_inicio', 'fecha_fin'], unique=False)

    op.create_table('user_known_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_known_ips', schema=None) as batch_op:
        batch_op.create_index('idx_user_ip', ['usuario_id', 'ip_address'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_known_ips', schema=None) as batch_op:
        batch_op.drop_index('idx_user_ip')

    op.drop_table('user_known_ips')
    with op.batch_alter_table('solicitudes_vacaciones', schema=None) as batch_op:
        batch_op.drop_index('idx_vacaciones_solape')
        batch_op.drop_index('idx_vacaciones_grupo')

    op.drop_table('solicitudes_vacaciones')
    with op.batch_alter_table('solicitudes_bajas', schema=None) as batch_op:
        batch_op.drop_index('idx_bajas_solape')
        batch_op.drop_index('idx_bajas_grupo')

    op.drop_table('solicitudes_bajas')
    with op.batch_alter_table('saldos_vacaciones', schema=None) as batch_op:
        batch_op.drop_index('idx_saldo_usuario_anio')
        batch_op.drop_index('idx_saldo_anio')

    op.drop_table('saldos_vacaciones')
    with op.batch_alter_table('fichajes', schema=None) as batch_op:
        batch_op.drop_index('idx_fichaje_usuario_fecha')
        batch_op.drop_index('idx_fichaje_grupo')
        batch_op.drop_index('idx_fichaje_fecha')

    op.drop_table('fichajes')
    with op.batch_alter_table('cambios_saldo', schema=None) as batch_op:
        batch_op.drop_index('idx_cambio_saldo_usuario')
        batch_op.drop_index('idx_cambio_saldo_fecha')

    op.drop_table('cambios_saldo')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index('idx_attachment_usuario')
        batch_op.drop_index('idx_attachment_entidad')

    op.drop_table('attachments')
    op.drop_table('aprobadores')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index('idx_usuario_email')
        batch_op.drop_index('idx_usuario_activo')

    op.drop_table('usuarios')
    op.drop_table('tipos_ausencia')
    with op.batch_alter_table('festivos', schema=None) as batch_op:
        batch_op.drop_index('idx_festivo_activo_fecha')

    op.drop_table('festivos')
    # ### end Alembic commands ###
